# Generated by Django 5.2.4 on 2025-07-18 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writers',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='writers',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writers',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='writers',
            name='title',
            field=models.CharField(default='dfa', max_length=255),
            preserve_default=False,
        ),
    ]
